"""add changes to table payments

Revision ID: 5a5983d0a5eb
Revises: b3f7a21452b0
Create Date: 2026-03-20 21:38:14.746113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5983d0a5eb'
down_revision: Union[str, Sequence[str], None] = 'b3f7a21452b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('booking_id', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'booking_id')
    # ### end Alembic commands ###
