"""add payment_method table

Revision ID: bfa64ed0f510
Revises: 9c7038c19135
Create Date: 2026-03-19 20:15:48.648395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa64ed0f510'
down_revision: Union[str, Sequence[str], None] = '9c7038c19135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_method_type', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', name='paymentmethodstatusenum'), nullable=False),
    sa.Column('bank', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('first6', sa.String(length=16), nullable=True),
    sa.Column('last4', sa.String(length=16), nullable=True),
    sa.Column('provider_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
